### PR TITLE
Updated CHANGELOG and documented examples

### PR DESCRIPTION
**Pull request by twolfson**
**Depends on #100**

In #99, we mentioned that we wanted to start documenting examples of setups. In this PR:

- Updated CHANGELOG
- Added examples to README (including #99)

/cc @wbond

### CODE REVIEW

**Comment by wbond** [comment]
LGTM!

**Comment by twolfson** [comment]
This has been merged/released in `1.10.1`

**Comment by twolfson** [comment]
@wbond We should probably update the project GitHub URL to its Package Control equivalent or remove it:

selection_192

**Comment by wbond** [comment]
Done, thanks for pointing that out!

**Pull request merged**
