### PR TITLE
Terminal.py corrected to work with non-ascii characters

### PR DESCRIPTION
**Pull request by Gebon**

### CODE REVIEW

**Comment by twolfson** [comment]
Can you provide an example of the problem you are encountering?

**Comment by Gebon** [comment]
I faced this problem when my profile in Windows had letters of the Russian
alphabet. I had error "UnicodeDecodeError: 'ascii' codec can't decode byte".

2015-06-13 15:44 GMT+05:00 Todd Wolfson <notifications@github.com>:

**Comment by twolfson** [comment]
I have tried reproducing the error but couldn't I created folders with "Д" in them as well as added "heyД" as a parameter.

Can you copy/paste your settings for Terminal, filepath you are attempting to open on, and which version of Sublime Text you are using?

**Comment by Gebon** [comment]
Well, I can't say to you my settings, because I've already reinstalled my
OS. But I remember, that path was like "C:\Users\Галлям\Documents..." etc,
and I touched nothing in Terminal settings. I used ST2. Now I'm using ST3,
and doesn't have this problem.

2015-06-14 2:18 GMT+05:00 Todd Wolfson <notifications@github.com>:

**Comment by twolfson** [comment]
Alright, I am going to eagerly close this issue since we have no way to verify the issue was patched once this is resolved =/

Hopefully if someone else is encountering the issue, then they will report it and we will reply/resolve it in a more timely fashion.

**Pull request closed without merging**
