### PR TITLE
Land PR #72

### PR DESCRIPTION
**Pull request by twolfson**
This PR adds an appropriate upgrade message and lands #72. In this PR:

- Landed #72 
- Added `1.8.0.txt` message
- Updated `messages.json` with new message

/cc @wbond (land when ready)

### CODE REVIEW

**Comment by wbond** [comment]
Seems to work fine to me.

The only thing I would change is remove the fenced code block around the json settings in the release message since that only formats in markdown.

**Comment by twolfson** [comment]
Ah, right. Sure thing

**Comment by twolfson** [comment]
This has been landed/released in `1.8.0`

**Comment by mbigras** [comment]
I'm running iTerm2 Build 2.1.4, after adding the `"--openNewTab"` parameter iTerm still opens in a new window. Also when removing the `"iTerm.sh"` parameter to use the default terminal, the tabbing functionality still doesn't work.

**Pull request merged**
