### PR TITLE
iTerm2 compatibility

### PR DESCRIPTION
**Pull request by luisc09**
Hi, 

I have been facing an issue trying to open the a window/tab in iTerm2. The fix was to update the application name to in the iTerm2-v3.sh script.

### CODE REVIEW

**Comment by twolfson** [comment]
Can you confirm that you had been using the script for a while and this only recently changed?

I'm concerned that while your computer has the application named as iTerm2, others might not

**Comment by luisc09** [comment]
> Can you confirm that you had been using the script for a while and this only recently changed?
> 
> I'm concerned that while your computer has the application named as iTerm2, others might not
Hi twolfson! 

I have consulted the iTerm2 documentation about [scripting](https://www.iterm2.com/documentation-scripting.html) and all examples uses `iTerm2`. I also noticed that in line [24](https://github.com/wbond/sublime_terminal/blob/master/iTerm2-v3.sh#L24) it is used `iTerm2` instead of `iTerm` which was kind of weird. 

I will keep an eye on this, and let you know if I face any issue, but so far so good! 😄 

Thanks!

**Comment by twolfson** [comment]
Great! I'll land this by the end of the weekend =) Thanks for all your work =D

**Comment by twolfson** [comment]
This has been landed and release in `1.21.0`. Thanks again for your work on this!

**Comment by luisc09** [comment]
I'm glad it helped! 

Thanks to you @twolfson!

**Comment by kitsguru** [comment]
I just did a resinstall of iterm2 via homebrew and the app is called iTerm.app, so this fix actually now breaks. If you download it from the https://www.iterm2.com/downloads.html it is called Term.app. This fix needs to be reverted.

**Comment by twolfson** [comment]
Ah, damn. Was worried about something like that. Reverting change for now. @luisc09 Maybe we can set this up so it takes a configuration for what the app is called?

**Comment by kitsguru** [comment]
now the iterm does not open in the project folder unless iterm is already open

**Comment by twolfson** [comment]
I only reverted the change. This must have been the behavior before (which
is a bug and should be its own issue) or maybe the change requires a delay
or restart

**Comment by kitsguru** [comment]
Iterm was updated recently as well, so a delay might be necessary. It does seem faster now.

**Comment by kitsguru** [comment]
I think I found a solution. It is necessary to activate the window first

```
#!/bin/bash

CD_CMD="cd "\\\"$(pwd)\\\"" && clear"
if echo "$SHELL" | grep -E "/fish$" &> /dev/null; then
    CD_CMD="cd "\\\"$(pwd)\\\""; and clear"
fi
VERSION=$(sw_vers -productVersion)
OPEN_IN_TAB=0

while [ "$1" != "" ]; do
    PARAM="$1"
    VALUE="$2"
    case "$PARAM" in
        --open-in-tab)
            OPEN_IN_TAB=1
            ;;
    esac
    shift
done

if (( $(expr $VERSION '<' 10.7) )); then
    RUNNING=$(osascript<<END
    tell application "System Events"
        count(processes whose name is "iTerm2")
    end tell
END
)
else
    RUNNING=1
fi

if (( ! $RUNNING )); then
    osascript<<END
    tell application "iTerm"
        tell current window
            activate
            tell current session
                write text "$CD_CMD"
            end tell
        end tell

    end tell
END
else
    if (( $OPEN_IN_TAB )); then

        osascript &>/dev/null <<EOF
        tell application "iTerm"
            if (count of windows) = 0 then
                set theWindow to (create window with default profile)
                set theSession to current session of theWindow
            else
                set theWindow to current window
                tell current window
                    set theTab to create tab with default profile
                    set theSession to current session of theTab
                end tell
            end if
            tell theSession
                write text "$CD_CMD"
            end tell

            activate
        end tell
EOF
    else
        osascript &>/dev/null <<EOF
        tell application "iTerm"
            tell (create window with default profile)
                tell the current session
                    write text "$CD_CMD"
                end tell
            end tell

            activate
        end tell
EOF
    fi
fi
```

**Comment by luisc09** [comment]
> Ah, damn. Was worried about something like that. Reverting change for now. @luisc09 Maybe we can set this up so it takes a configuration for what the app is called?

Ah, sorry about that 😞 

Yes, let me check what it can be done.

**Pull request merged**
