### PR TITLE
Open a terminal in a new tab of the first iTerm

### PR DESCRIPTION
**Pull request by Starli0n**
Hi,

I made an update so that if iTerm is not running, it is launched.
If it is running, open a new tab of the first iTerm

Hope it helps

### CODE REVIEW

**Comment by trevordmiller** [comment]
+1. Please merge this :)

**Comment by Pixelalb** [comment]
This is not working for me. It still opens new iTerm window

**Comment by twolfson** [comment]
I don't think we want to break the existing new window functionality. This should be done via an opt-in setting somehow.

There seems to be another PR #72 which is a few steps ahead of this one. I am going to consider this a duplicate for now =/

**Comment by twolfson** [comment]
As a heads up, #72 has added support for opening via a new tab in `1.8.0`.

**Pull request closed without merging**
