### PR TITLE
Convert readme.creole to markdown README.md

### PR DESCRIPTION
**Pull request by tekwiz**
Since your newer projects are using Markdown and Markdown is pretty much the defacto standard, I am
submitting this simple conversion if you desire to make the switch.

### CODE REVIEW

**Comment by twolfson** [comment]
It looks like @wbond had a change of heart from creole to Markdown in Aug 2013.

https://github.com/wbond/package_control_channel/commit/e858c4db848efe86164fa16685a89b36d2090bfd

@wbond Thoughts on this PR? I am fine landing it if you approve.

Side note: We should update the text in a following PR to not say ST2 anymore x_x

**Comment by wbond** [comment]
Yeah, Markdown is great. It has basically become the de facto standard.

**Comment by twolfson** [comment]
Cool, will land within the next week :+1:

**Comment by twolfson** [comment]
Upon re-reviewing, I would prefer to stick with the `#` to keep things consistent among @wbond's repos.

https://raw.githubusercontent.com/wbond/package_control_channel/7d0858948c54f9dbfa46646f759c0100c3e3d5ab/readme.md

@tekwiz Can you update this PR to line up more with that? (e.g. use `#` for headings, name it `readme.md` instead of `README.md`)

**Comment by shivapoudel** [comment]
+1

**Comment by twolfson** [comment]
Closing PR due to inactivity. Replacing with PR #100.

**Pull request closed without merging**
