### PR TITLE
Update iTerm2-v3.sh

### LINKED ISSUE #208: iterm2 does not open and change directory on first call
In issue #207, it was noted that iterm2 did not cd to the project directory.  The solution is to activate the window then tell the session to cd

```
#!/bin/bash

CD_CMD="cd "\\\"$(pwd)\\\"" && clear"
if echo "$SHELL" | grep -E "/fish$" &> /dev/null; then
    CD_CMD="cd "\\\"$(pwd)\\\""; and clear"
fi
VERSION=$(sw_vers -productVersion)
OPEN_IN_TAB=0

while [ "$1" != "" ]; do
    PARAM="$1"
    VALUE="$2"
    case "$PARAM" in
        --open-in-tab)
            OPEN_IN_TAB=1
            ;;
    esac
    shift
done

if (( $(expr $VERSION '<' 10.7) )); then
    RUNNING=$(osascript<<END
    tell application "System Events"
        count(processes whose name is "iTerm2")
    end tell
END
)
else
    RUNNING=1
fi

if (( ! $RUNNING )); then
    osascript<<END
    tell application "iTerm"
        tell current window
            activate
            tell current session
                write text "$CD_CMD"
            end tell
        end tell

    end tell
END
else
    if (( $OPEN_IN_TAB )); then

        osascript &>/dev/null <<EOF
        tell application "iTerm"
            if (count of windows) = 0 then
                set theWindow to (create window with default profile)
                set theSession to current session of theWindow
            else
                set theWindow to current window
                tell current window
                    set theTab to create tab with default profile
                    set theSession to current session of theTab
                end tell
            end if
            tell theSession
                write text "$CD_CMD"
            end tell

            activate
        end tell
EOF
    else
        osascript &>/dev/null <<EOF
        tell application "iTerm"
            tell (create window with default profile)
                tell the current session
                    write text "$CD_CMD"
                end tell
            end tell

            activate
        end tell
EOF
    fi
fi

```

### PR DESCRIPTION
**Pull request by kitsguru**
fix #208 iterm2 change directory on first call

### CODE REVIEW

**Comment by twolfson** [comment]
Looks good to me though I'd like to undo a lot of the unnecessary whitespace changes. I don't have much time to land this immediately. I will land it by the end of the month

**Comment by kitsguru** [comment]
I was looking for an editorconfig file, but used my default.

**Comment by twolfson** [comment]
Thanks for all your work on this! This has been landed and released in `1.23.0`

**Comment by twolfson** [comment]
If you'd like to help us add an `editorconfig` file, it'd be much appreciated =)

**Comment by kitsguru** [comment]
I have been away and playing catchup since getting back and would be happy to create the editorconfig file however mine is different from what you have been using and I am not sure what settings you prefer.
tabs or spaces and 2 or 4 spaces if applicable?

**Comment by twolfson** [comment]
I've been using what seems to be the convention in the files (Sublime Text auto-configures when a file is opened). It looks like:

- Python, 4 spaces
- Shell, tabs (looks like `hyper.sh` missed this convention)

**Pull request merged**
