### PR TITLE
Replaced readme.creole with readme.md based off of website

### PR DESCRIPTION
**Pull request by twolfson**
This PR is a replacement for #47 and catalyzed by #99. This PR takes the contents of http://wbond.net/sublime_packages/terminal and moves them into this repo's `readme.md`/`changelog.md`. In this PR:

- Replaced readme.creole with readme.md based off of website
- Moved Changelog contents into `changelog.md`
- Moved License into `LICENSE`

**Notes:**

We tried out best to keep the formatting consistent with @wbond's other repos. For example:

- 1 new line after each heading
- 1 space before each `-`
- Usage of `[]()` for links, not `[][]` format
- Usage of lowercase `readme.md` name
- Usage of lowercase `changelog.md`
- Usage of separate `changelog.md` and `LICENSE`

Source: https://github.com/codexns/newterm

/cc @wbond

### CODE REVIEW

**Comment by twolfson** [comment]
I should also note that there is no new content here. That will be coming in a follow-up PR.

**Comment by twolfson** [comment]
@wbond Any chance of a :+1: on this and #101?

**Comment by wbond** [comment]
Sorry, looks like I commented on your repo's history rather than this PR.

Other than those URL fixes and removing the screenshots, it LGTM.

**Comment by twolfson** [comment]
For future reference, the original comments were on https://github.com/twolfson/sublime_terminal/commit/329c45f753827f68e61ab7fd2f3c1a9696699ada

**Comment by twolfson** [comment]
This has been merged/released in `1.10.1`

**Pull request merged**
